language: minimal
sudo: required
dist: bionic
env:
  matrix:
    - EMACS=emacs25
    - EMACS=emacs26

install:
  - if [ "$EMACS" = 'emacs26' ]; then
        sudo add-apt-repository -y ppa:kelleyk/emacs &&
        sudo apt-get update &&
        sudo apt-get -qq -f install &&
        sudo apt-get -qq install emacs26 emacs26-el;
    fi

script:
  - make all

notifications:
  email: false
